[build]
  # Directory to change to before starting a build. 
  # This is where we will look for package.json/.nvmrc/etc.
  base = "/"

  # Directory that contains the deploy-ready files
  publish = "dist/public"

  # Default build command
  command = "bash ./netlify-build.sh"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "20"

[functions]
  # Directory with serverless functions
  directory = "dist/functions"
  # Increase timeout to 30 seconds
  node_bundler = "esbuild"
  
  [functions.api]
    timeout = 30

# Redirect www to non-www
[[redirects]]
  from = "https://www.howto-ai.netlify.app/*"
  to = "https://howto-ai.netlify.app/:splat"
  status = 301
  force = true

# API redirects to Netlify Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect all other paths to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set cache headers for images
[[headers]]
  for = "*.{jpg,jpeg,png,svg,gif,webp}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self' *; script-src 'self' 'unsafe-inline' 'unsafe-eval' * groptoxegri.com *.groptoxegri.com; style-src 'self' 'unsafe-inline' *; img-src 'self' data: blob: *; connect-src 'self' https://api.anthropic.com *; font-src 'self' *; object-src 'none'; media-src 'self' *; frame-src 'self' *;"