import { Guide, GuideSection } from "@shared/schema";
import { jsPDF } from "jspdf";
import 'jspdf-autotable';

// Add the missing interface for jsPDF-autotable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

export const generatePDF = (guide: Guide) => {
  // Create new PDF document
  const doc = new jsPDF();
  
  // Set title
  doc.setFontSize(22);
  doc.text(guide.title, 14, 22);
  
  // Add date
  const formattedDate = new Date(guide.createdAt).toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on ${formattedDate} by HowTo.AI`, 14, 30);
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  let yPosition = 40;
  
  // Add content
  doc.setFontSize(12);
  
  // Loop through sections
  (guide.content.sections as GuideSection[]).forEach((section, index) => {
    // Add section title
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    
    // Check if new page is needed
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }
    
    doc.text(section.title, 14, yPosition);
    yPosition += 8;
    
    // Reset font
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    
    // Add section content
    if (section.type === "list" && section.items) {
      section.items.forEach((item, itemIndex) => {
        // Check if new page is needed
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        
        doc.text(`• ${item}`, 16, yPosition);
        yPosition += 7;
      });
    } else if (section.content) {
      section.content.forEach((paragraph, paragraphIndex) => {
        // Check if paragraph will fit on page, if not add a new page
        const textLines = doc.splitTextToSize(paragraph, 180);
        if (yPosition + (textLines.length * 7) > 280) {
          doc.addPage();
          yPosition = 20;
        }
        
        // Add the paragraph text
        doc.text(textLines, 14, yPosition);
        yPosition += textLines.length * 7 + 3;
      });
    }
    
    yPosition += 5;
  });
  
  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(
      'Generated by HowTo.AI',
      14,
      doc.internal.pageSize.height - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 30,
      doc.internal.pageSize.height - 10
    );
  }
  
  // Save the PDF
  doc.save(`${guide.title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
};
